// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckVersion() {
  return window['go']['main']['AppService']['CheckVersion']();
}

export function ClearAttachments() {
  return window['go']['main']['AppService']['ClearAttachments']();
}

export function ClearLog() {
  return window['go']['main']['AppService']['ClearLog']();
}

export function GetAttachments() {
  return window['go']['main']['AppService']['GetAttachments']();
}

export function GetConfigPath() {
  return window['go']['main']['AppService']['GetConfigPath']();
}

export function GetVersion() {
  return window['go']['main']['AppService']['GetVersion']();
}

export function HasPassword(arg1) {
  return window['go']['main']['AppService']['HasPassword'](arg1);
}

export function IsSending() {
  return window['go']['main']['AppService']['IsSending']();
}

export function LoadConfig() {
  return window['go']['main']['AppService']['LoadConfig']();
}

export function LoadConfigFrom() {
  return window['go']['main']['AppService']['LoadConfigFrom']();
}

export function LoadPassword(arg1) {
  return window['go']['main']['AppService']['LoadPassword'](arg1);
}

export function ParseEMLPreview(arg1) {
  return window['go']['main']['AppService']['ParseEMLPreview'](arg1);
}

export function RemoveAttachment(arg1) {
  return window['go']['main']['AppService']['RemoveAttachment'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['AppService']['SaveConfig'](arg1);
}

export function SavePassword(arg1, arg2) {
  return window['go']['main']['AppService']['SavePassword'](arg1, arg2);
}

export function SaveWindowState(arg1) {
  return window['go']['main']['AppService']['SaveWindowState'](arg1);
}

export function SelectAttachments() {
  return window['go']['main']['AppService']['SelectAttachments']();
}

export function SelectEMLFiles() {
  return window['go']['main']['AppService']['SelectEMLFiles']();
}

export function StartSend() {
  return window['go']['main']['AppService']['StartSend']();
}

export function StartSendEML(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['AppService']['StartSendEML'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function StopSend() {
  return window['go']['main']['AppService']['StopSend']();
}

export function SyncConfig(arg1) {
  return window['go']['main']['AppService']['SyncConfig'](arg1);
}

export function TestConnection() {
  return window['go']['main']['AppService']['TestConnection']();
}
