// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function CheckVersion():Promise<core.VersionCheckResult>;

export function ClearAttachments():Promise<void>;

export function ClearLog():Promise<void>;

export function GetAttachments():Promise<Array<string>>;

export function GetConfigPath():Promise<string>;

export function GetVersion():Promise<string>;

export function IsSending():Promise<boolean>;

export function LoadConfig():Promise<core.AppConfig>;

export function LoadConfigFrom():Promise<core.AppConfig>;

export function LoadPassword(arg1:string):Promise<string>;

export function ParseEMLPreview(arg1:string):Promise<core.EMLPreview>;

export function RemoveAttachment(arg1:number):Promise<Array<string>>;

export function SaveConfig(arg1:core.AppConfig):Promise<void>;

export function SavePassword(arg1:string,arg2:string):Promise<void>;

export function SaveWindowState(arg1:core.WindowState):Promise<void>;

export function SelectAttachments():Promise<Array<string>>;

export function SelectEMLFiles():Promise<Array<string>>;

export function StartSend():Promise<void>;

export function StartSendEML(arg1:Array<string>,arg2:string,arg3:string,arg4:boolean,arg5:boolean,arg6:boolean,arg7:boolean,arg8:number,arg9:number,arg10:number):Promise<void>;

export function StopSend():Promise<void>;

export function SyncConfig(arg1:core.AppConfig):Promise<void>;

export function TestConnection():Promise<void>;
